version: '3'

tasks:
  test:
    desc: Run unit tests.
    cmds:
      - go test -race -v ./...

  lint:
    desc: Run linters.
    cmds:
      - revive .

  fuzz:
    desc: Run fuzz tests.
    cmds:
      - go test -fuzz=Fuzz -fuzztime 30s .

  bench:
    desc: Run benchmarks.
    cmds:
      - go test -bench=. -benchmem
