version: '3'

tasks:
  test:
    desc: Run unit tests.
    cmds:
      - go test -v ./...

  fuzz:
    desc: Run fuzz tests.
    cmds:
      - go test -fuzz=FuzzRing$ -fuzztime 30s .
      - go test -fuzz=FuzzRingWrite -fuzztime 30s .

  bench:
    desc: Run benchmarks.
    cmds:
      - go test -bench=. -benchmem
